HAI
I HAS a ITZ 1
I HAS b ITZ 1
I HAS n ITZ 0
I HAS i ITZ 2
VISIBLE i
VISIBLE a
GIMMEH n
  O RLY EITHER SAEM n AN 1 AN SAEM n AN 2 ?
    YA RLY, VISIBLE 1, KTHXBYE
  OIC
IM IN YR LOOP
  LOL i IZ SUM OF i AN 1
  LOL b IZ SUM OF b AN a
  LOL a IZ DIFF OF b AN a
  O RLY SAEM i AN n ?
    YA RLY, GTFO
  OIC
IM OUTTA YR LOOP
VISIBLE b
KTHXBYE