HAI
I HAS SUMA
I HAS X
LOL X IZ 0
LOL SUMA IZ 0
IM IN YR LOOP
   VISIBLE "petla"
   LOL X IZ SUM OF X AN 1
   LOL SUMA IZ SUM OF SUMA AN X
   O RLY SAEM X AN 100 ?
      YA RLY, GTFO
   OIC
IM OUTTA YR LOOP
VISIBLE "suma"
VISIBLE SUMA
